<?php

return [
    'scan_dirs' => [
        'framework/UX',
        'framework/View',
        'framework/Component',
        'admin/Component',
        'admin/Pages',
        'app/Component',
        'admin/Contracts/Live'
    ],

    'always_generated' => [
        'opacity-0', 'opacity-100', 'scale-90', 'scale-95', 'scale-100',
        'translate-y-full', 'translate-x-full', 'translate-y-0', 'translate-x-0',
        'flex-row', 'flex-row-reverse', 'flex-col', 'flex-col-reverse',
        'flex-wrap', 'flex-wrap-reverse', 'flex-nowrap',
        'justify-start', 'justify-end', 'justify-center', 'justify-between', 'justify-around', 'justify-evenly',
        'items-start', 'items-end', 'items-center', 'items-baseline', 'items-stretch',
        'flex', 'inline-flex', 'grid', 'block', 'hidden',
        'gap-0', 'gap-0.5', 'gap-1', 'gap-1.5', 'gap-2', 'gap-3', 'gap-4', 'gap-5', 'gap-6', 'gap-8', 'gap-10', 'gap-12',
        'p-0', 'p-0.5', 'p-1', 'p-1.5', 'p-2', 'p-3', 'p-4', 'p-5', 'p-6', 'p-8', 'p-10', 'p-12',
        'px-0', 'px-0.5', 'px-1', 'px-1.5', 'px-2', 'px-3', 'px-4', 'px-5', 'px-6', 'px-8',
        'py-0', 'py-0.5', 'py-1', 'py-1.5', 'py-2', 'py-3', 'py-4', 'py-5', 'py-6', 'py-8',
        'm-0', 'm-0.5', 'm-1', 'm-1.5', 'm-2', 'm-3', 'm-4', 'm-5', 'm-6', 'm-8', 'm-10', 'm-12',
        'mb-0', 'mb-0.5', 'mb-1', 'mb-1.5', 'mb-2', 'mb-3', 'mb-4', 'mb-5', 'mb-6', 'mb-8',
        'mt-0', 'mt-0.5', 'mt-1', 'mt-1.5', 'mt-2', 'mt-3', 'mt-4', 'mt-5', 'mt-6', 'mt-8',
        'mr-0', 'mr-0.5', 'mr-1', 'mr-1.5', 'mr-2', 'mr-3', 'mr-4', 'mr-6', 'mr-8',
        'ml-0', 'ml-0.5', 'ml-1', 'ml-1.5', 'ml-2', 'ml-3', 'ml-4', 'ml-6', 'ml-8',
        'mx-0', 'mx-0.5', 'mx-1', 'mx-1.5', 'mx-2', 'mx-3', 'mx-4', 'mx-6', 'mx-8', 'mx-auto',
        'my-0', 'my-0.5', 'my-1', 'my-1.5', 'my-2', 'my-3', 'my-4', 'my-6', 'my-8', 'my-auto',
        'min-h-screen', 'min-h-full', 'min-h-0',
        'max-h-screen', 'max-h-full',
        'overflow-auto', 'overflow-hidden', 'overflow-visible', 'overflow-scroll',
        'overflow-x-auto', 'overflow-y-auto',
        'border', 'border-0', 'border-t', 'border-r', 'border-b', 'border-l',
        'border-solid', 'border-dashed',
        'bg-white', 'bg-gray-50', 'bg-gray-100', 'bg-gray-200',
        'bg-blue-50', 'bg-blue-100', 'bg-blue-500', 'bg-blue-600',
        'bg-green-50', 'bg-green-100', 'bg-green-500',
        'bg-red-50', 'bg-red-100', 'bg-red-500',
        'bg-yellow-50', 'bg-yellow-100',
        'rounded', 'rounded-sm', 'rounded-md', 'rounded-lg', 'rounded-xl', 'rounded-full', 'rounded-none',
        'rounded-t', 'rounded-r', 'rounded-b', 'rounded-l',
        'max-w-lg', 'max-w-md', 'max-w-sm', 'max-w-xs', 'max-w-xl', 'max-w-2xl', 'max-w-4xl', 'max-w-full',
        'w-full', 'w-auto', 'h-full', 'h-auto', 'h-screen',
        'text-xs', 'text-sm', 'text-base', 'text-lg', 'text-xl', 'text-2xl', 'text-3xl',
        'font-thin', 'font-light', 'font-normal', 'font-medium', 'font-semibold', 'font-bold', 'font-extrabold',
        'text-left', 'text-center', 'text-right',
        'text-white', 'text-gray-500', 'text-gray-600', 'text-gray-700', 'text-gray-800', 'text-gray-900',
        'text-blue-500', 'text-blue-600', 'text-blue-700',
        'text-red-500', 'text-red-600',
        'text-green-500', 'text-green-600',
        'leading-none', 'leading-tight', 'leading-snug', 'leading-normal', 'leading-relaxed', 'leading-loose',
        'tracking-tight', 'tracking-normal', 'tracking-wide', 'tracking-wider',
        'cursor-pointer', 'cursor-default', 'cursor-not-allowed', 'cursor-wait', 'cursor-move',
        'select-none', 'select-auto', 'select-text',
        'pointer-events-none', 'pointer-events-auto',
        'list-none', 'list-disc', 'list-decimal',
        'space-y-0', 'space-y-0.5', 'space-y-1', 'space-y-2', 'space-y-3', 'space-y-4', 'space-y-6', 'space-y-8',
        'space-x-0', 'space-x-1', 'space-x-2', 'space-x-4',
        'grid-cols-1', 'grid-cols-2', 'grid-cols-3', 'grid-cols-4', 'grid-cols-6', 'grid-cols-12',
        'col-span-1', 'col-span-2', 'col-span-3', 'col-span-4', 'col-span-6', 'col-span-full',
        'truncate', 'whitespace-nowrap', 'whitespace-normal', 'whitespace-pre',
        'break-words', 'break-all',
        'shadow', 'shadow-sm', 'shadow-md', 'shadow-lg', 'shadow-xl', 'shadow-none',
        'outline-none', 'outline',
        'ring-0', 'ring-1', 'ring-2', 'ring-4',
        'transition', 'transition-all', 'transition-colors', 'transition-opacity', 'transition-transform',
        'duration-75', 'duration-100', 'duration-150', 'duration-200', 'duration-300', 'duration-500',
        'ease-linear', 'ease-in', 'ease-out', 'ease-in-out',
        'z-0', 'z-10', 'z-20', 'z-30', 'z-40', 'z-50',
        'inset-0',
        'top-0', 'right-0', 'bottom-0', 'left-0',
        'absolute', 'relative', 'fixed', 'sticky',
        'table', 'table-row', 'table-cell', 'table-header-group', 'table-body-group',
        'appearance-none',
        'sr-only',
    ],
];
